# Generated by Django 3.0.6 on 2020-05-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_editing_approved',
            field=models.BooleanField(default=False),
        ),
    ]
