# Generated by Django 3.0.6 on 2020-05-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200519_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='keywords',
            field=models.CharField(max_length=50, verbose_name='Keywords'),
        ),
    ]
